language: rust
rust:
  - stable
  - beta
  - 1.26.0
cache: cargo

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --verbose --features 'kafka_submitter redis_authenticator'
  - cargo test --verbose --features 'kafka_submitter redis_authenticator'
