language: rust
rust:
  - stable
  - beta
  - 1.26.0
cache: cargo

script:
  - cargo build --verbose
  - cargo test --verbose
  - if [ "$(rustup show | grep default | grep stable)" != "" ]; then cargo build --verbose --features 'kafka_submitter redis_authenticator'; fi
  - if [ "$(rustup show | grep default | grep stable)" != "" ]; then cargo test --verbose --features 'kafka_submitter redis_authenticator'; fi
